### ISSUE TITLE
no alias for tmpstandard league?

### ISSUE THREAD

**Issue by Davst** [siegrest/poewatch#48]
I've looked through the API documentation and it seems that there is no abstracted way to reference the current temporary league, most oftenly referred to tmpstandard and tmphardcore in other apps and APIs. 

I'd love if this feature became available as an alias to the currently active temp league.

**Comment by siegrest** [comment]
I left it out initially as the [official league api](http://api.pathofexile.com/leagues?type=main) doesn't have that indication either. Could flag temp leagues based on guesswork (eg not permanent and not an event), though I'm not sure how it'd behave in edge cases when there's a challenge league and a flashback concurrently.

**Comment by siegrest** [comment]
Fixed in 442c6b49a6c9167d7766b2dd11f70f55192d879e. Closed due to inactivity.
