### ISSUE TITLE
No Betrayal data

### ISSUE THREAD

**Issue by H4xoltl** [siegrest/poewatch#56]
Hey guys,

there doesn't seem to be any data from Betrayal league. i.e. trying to search for the prices of divination cards in 3.5.0 returns nothing

**Comment by siegrest** [comment]
Fixed in 0c94b1f1d61a000dcc8de44d93cca25800e0f2cd. 
Refresh page (or force refresh with `Ctrl`+`F5`) for changes to take effect.
