### ISSUE TITLE
Missing chart data at /prices

### ISSUE THREAD

**Issue by fladson** [siegrest/poewatch#61]
Hello @siegrest 
Thanks for the awesome application you've put together, really useful and well done.

I am seeing the `{{meta}}` tag on all charts when hovering, is that expected?

**Comment by siegrest** [comment]
Cheers! That happened when older js files were loaded from cache. Should've been fixed yesterday with a basic url busting method. Is it still occurring?

**Comment by fladson** [comment]
Yeah, it is still occurring but I can't load the application anymore to check without cache.
`poe.watch’s server IP address could not be found.`

**Comment by siegrest** [comment]
Had some DNS troubles while migrating machines. Site should be up and running now.

**Comment by fladson** [comment]
A hard refresh solved it, ty.
